# Site settings
title: Acacia Fraternity UW
social:
  -
    text: Facebook
    link: https://www.facebook.com/UWacacia/
    icon: fa-facebook-square
  -
    text: Twitter
    link: http://twitter.com/acaciauw
    icon: fa-twitter-square
  -
    text: Email
    link: uw23@acacia.org
    prefix: 'mailto:'
    icon: fa-envelope-square
  -
    text: (425) 736-9102
    link: 14257369102
    prefix: 'tel:'
    icon: fa-phone-square
description: "Official page of the Acacia Fraternity at the University of Washington"
keywords: "Acacia UW University Washington Seattle Fraternity AKAK AK Brotherhood"
baseurl: "/acacia-web"
url: "http://washingtonacacia.org"

# Build settings
markdown: kramdown
permalink: pretty
