# Site settings
title: Acacia Fraternity UW
social:
  -
    text: Facebook
    class: facebook
    link: https://www.facebook.com/UWacacia/
    icon: fa-facebook-square
  -
    text: Twitter
    class: twitter
    link: http://twitter.com/acaciauw
    icon: fa-twitter-square
email:
  text: uw23@acacia.org
  class: email
  link: uw23@acacia.org
  icon: fa-envelope-square
phone:
  text: (425) 749-8961
  class: phone
  link: 14257498961
  icon: fa-phone-square
gallery:
    -
        url: /assets/gallery/gameday.jpg
        title: Gameday
    -
        url: /assets/gallery/mountain.jpg
        title: Outdoors
    -
        url: /assets/gallery/rush.jpg
        title: Game Night at the HUB
    -
        url: /assets/gallery/working.jpg
        title: Community Service
    -
        url: /assets/gallery/foundingfathers-1904.jpg
        title: Original Founding Fathers
    -
        url: /assets/gallery/foundingfathers.jpg
        title: Recolonization Founding Fathers
    -
        url: /assets/gallery/working-2.jpg
        title: Community Service
description: "Official page of the Acacia Fraternity at the University of Washington"
keywords: "Acacia UW University Washington Seattle Fraternity AKAK AK Brotherhood"
baseurl: "/acacia-web"
url: "http://washingtonacacia.org"

# Build settings
markdown: kramdown
permalink: pretty

# Compress settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]