# Site settings
title: Acacia Fraternity UW
email: uw23@acacia.org
phone: 14257369102
phoneclean: (425) 736-9102
facebook: https://www.facebook.com/UWacacia/
twitter: http://twitter.com/acaciauw
description: "Official page of the Acacia Fraternity at the University of Washington"
keywords: "Acacia UW University Washington Seattle Fraternity AKAK AK Brotherhood"
baseurl: ""
url: "http://washingtonacacia.org/"

# Build settings
markdown: kramdown
permalink: pretty
